# AUTOGRAD: AUTOMATIC DIFFERENTIATION

## autograd

In [1]:
import torch
x = torch.ones(2,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [2]:
y = x+2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [3]:
# y was created as a result of an operation, so it has a grad_fn.
print(y.grad_fn)

In [5]:
z = y*y*3
out = z.mean()
print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


In [8]:
a = torch.randn(2, 2)
print(a)
a = ((a * 3) / (a - 1))
print(a)
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

tensor([[-0.7479, -1.6744],
        [ 0.6169,  0.1691]])
tensor([[ 1.2837,  1.8783],
        [-4.8310, -0.6105]])
False
True


## Gradients

In [11]:
print(out)

tensor(27., grad_fn=<MeanBackward0>)


In [9]:
out.backward()

In [10]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [15]:
x = torch.rand(3,requires_grad=True)
y = x*2
print(y)
while y.data.norm() < 1000:
    y = y*2
print(y)    

tensor([0.1847, 0.6207, 1.2807], grad_fn=<MulBackward0>)
tensor([ 189.1740,  635.6268, 1311.4679], grad_fn=<MulBackward0>)


In [13]:
'''
Now in this case y is no longer a scalar. torch.autograd could not compute the full Jacobian directly,
but if we just want the vector-Jacobian product, simply pass the vector to backward as argument:
'''


In [22]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
print(v)
# y.backward(v)
# print(x.grad)

tensor([1.0000e-01, 1.0000e+00, 1.0000e-04])


In [23]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
