# Tensors

In [2]:
from __future__ import print_function
import torch

In [7]:
# An uninitialized matrix ; these values in n uninitialized are  Arbitrary value in our memory ; 
# so  this matrix is called   An uninitialized matrix

x = torch.empty(5, 3)
print(x)
print(x.size())
print(x.size(0))
print(x.size(1))

tensor([[-1.5702e-09,  4.5682e-41, -1.5702e-09],
        [ 4.5682e-41,  4.4842e-44,  0.0000e+00],
        [ 8.9683e-44,  0.0000e+00, -6.5492e-39],
        [ 3.0865e-41,  8.9683e-44,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])
torch.Size([5, 3])
5
3


In [10]:
# Construct a randomly initialized matrix:
x = torch.rand(5, 3)
print(x)

tensor([[0.9023, 0.7620, 0.8056],
        [0.6631, 0.2539, 0.9194],
        [0.4668, 0.0289, 0.8913],
        [0.1092, 0.2412, 0.3686],
        [0.3479, 0.7714, 0.8702]])


In [12]:
# Construct a matrix filled zeros and of dtype long:
# define data type
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [14]:
# Construct a tensor directly from data:
x = torch.tensor([5.5, 3])
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([5.5000, 3.0000])


In [16]:
# define all values 1  matrix 
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

# overwrite our matrix here and the size the same 
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.1374,  2.4879, -1.2088],
        [ 1.2377, -0.2502, -0.0390],
        [-1.2462,  0.0225,  1.5966],
        [-0.3117, -0.4609, -0.7344],
        [ 1.2797,  0.4174,  0.3062]])


In [17]:
# Operations
y = torch.rand(5,3)
print(x+y)

tensor([[ 2.0729,  2.8382, -0.7127],
        [ 1.8837,  0.2907,  0.1853],
        [-0.8126,  0.7166,  2.5009],
        [ 0.4042,  0.1780,  0.2488],
        [ 1.3099,  1.0800,  1.2435]])


In [18]:
# use method 
print(torch.add(x,y))

tensor([[ 2.0729,  2.8382, -0.7127],
        [ 1.8837,  0.2907,  0.1853],
        [-0.8126,  0.7166,  2.5009],
        [ 0.4042,  0.1780,  0.2488],
        [ 1.3099,  1.0800,  1.2435]])


In [19]:
# Addition: providing an output tensor as argument
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[ 2.0729,  2.8382, -0.7127],
        [ 1.8837,  0.2907,  0.1853],
        [-0.8126,  0.7166,  2.5009],
        [ 0.4042,  0.1780,  0.2488],
        [ 1.3099,  1.0800,  1.2435]])


In [20]:
# Addition: in-place
print(y.add(x))


tensor([[ 2.0729,  2.8382, -0.7127],
        [ 1.8837,  0.2907,  0.1853],
        [-0.8126,  0.7166,  2.5009],
        [ 0.4042,  0.1780,  0.2488],
        [ 1.3099,  1.0800,  1.2435]])


In [21]:
print(x[:, 1])

tensor([ 2.4879, -0.2502,  0.0225, -0.4609,  0.4174])


In [22]:
# resize/reshape tensor
x = torch.rand(4,4)

In [23]:
x

tensor([[0.7162, 0.6508, 0.1703, 0.6619],
        [0.1648, 0.9518, 0.4104, 0.4347],
        [0.9741, 0.3888, 0.4969, 0.9224],
        [0.0901, 0.6819, 0.9134, 0.4725]])

In [25]:
y = x.view(16)
y

tensor([0.7162, 0.6508, 0.1703, 0.6619, 0.1648, 0.9518, 0.4104, 0.4347, 0.9741,
        0.3888, 0.4969, 0.9224, 0.0901, 0.6819, 0.9134, 0.4725])

In [26]:
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
z

tensor([[0.7162, 0.6508, 0.1703, 0.6619, 0.1648, 0.9518, 0.4104, 0.4347],
        [0.9741, 0.3888, 0.4969, 0.9224, 0.0901, 0.6819, 0.9134, 0.4725]])

In [27]:
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [28]:
# get the value from tensor 
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.5470])
-0.5470423102378845


In [29]:
# Converting a Torch Tensor to a NumPy Array
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [30]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [31]:
# Converting NumPy Array to Torch Tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
